### PR TITLE
Add Gitea as source

### LINKED ISSUE #1: Integrating Gitea as Source
Hey @creativeprojects ,
awesome to see somebody making go-github-selfupdate more generic

What are you plans with this ? Will you keep maintaining it ?

If so I would add support for Gitea (in a PR), as your abstractions for sources and eleases already make it really straight forward to do so! (I actually started with making the updater genric for half an hour, than  procrastination and googling brought me here 😅)

Greetings,
Lukas

### PR DESCRIPTION
**Pull request by s00500**
### Adds Gitea as possible source for updates (Closes #1)
Also needs to support GITEA_TOKEN

#### TODO:
- [x] Tests
- [x] Docs
- [x] Update examples for custom sources

Maybe: Add helper to ease configuring the updater for custom sources ?

### CODE REVIEW

**Comment by s00500** [comment]
Ok, this works fine now, my examples and docs are limited so far though...

What do you think ? @creativeprojects

**Comment by creativeprojects** [comment]
I'll look at it in more details in the next couple of days but it looks good so far

**Comment by creativeprojects** [comment]
@s00500 right it looks pretty straightforward. Gitea API is unsurprisingly similar to GitHub.

To avoid confusion, I would put a note in the GitHub methods asking for a ReleaseID that it's not in use in this case.

May I ask why you need an AssetName as well as the AssetURL? Is it because asset urls don't contain the name of the asset in them?

**Comment by s00500** [comment]
The note makes sense,
Yes, the gitea AssetURLS end with something like a uuid, no name that can help decode what compression format is used, so we need to pass it along.... I have been thinking of using the release structure to be passed around, making that stuff a little easier...

**Comment by s00500** [comment]
Shall we proceed with this / shall I make changes :-) ?

**Comment by creativeprojects** [comment]
Yeah sorry I was working on some other things, I'll merge this and update the documentation.

Thanks 👍🏻

**Pull request merged**
